#!/bin/sh

query="$*"

new_line='
'
# to trick 9anime that a browser is being used
curl_headers="
-H 'authority: 9anim.vip'
-H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36'
-H 'referer: https://9anim.vip/serie/1068/sword-art-online.html'
"
curl_headers=
tab_space=$(printf '\t')

die () {
	printf '%s\n' "$*" >&2
	exit 1;
}

##########################
# PREPARING SEARCH QUERY #
##########################
# prepend + before each word, and remove the first words +
# to get a + separated query
query_string=
for word in $query; do
	query_string=${query_string}+${word}
done
query_string=${query_string#+}

###########################
# GETTING THE SEARCH PAGE #
###########################
html=$(
curl -s "https://9anim.vip/search" \
	-G -d "q=$query_string" $curl_headers
)

#########################################
# PARSING AND DISPLAYING THE ANIME LIST #
#########################################
anime_url_list=
anime_count=0
while IFS= read line; do
	case $line in
		'<a href="/serie/'*|'<a href="/movie/'*)
			anime_count=$((anime_count+1))
			IFS=\" read _ url _ name _ <<-!
			$line
			!
			# append the anime name and its url to the list
			anime_url_list=${anime_url_list}${new_line}${url}
			# print the anime name
			printf '[%d] %s\n' $anime_count "$name"
			;;
		'<span>Dubbed</span>'*)
			printf '    Dubbed\n'
	esac
done<<!
$html
!
anime_url_list=${anime_url_list#$new_line}
[ $anime_count -eq 0 ] && die "no search results"

##############################
# SELECTING THE ANIME CHOICE #
##############################
read selected_anime_count
count=0
while read url; do
	count=$((count+1))
	if [ $count -eq $selected_anime_count ]; then
		selected_anime_url=$url
	fi
done<<!
$anime_url_list
!
[ -z "$selected_anime_url" ] && die "invalid choice"

##########################
# GETTING THE ANIME PAGE #
##########################

play_ep () {
	html=$(
		curl -s "https://9anim.vip/ajax/${ep_type}/downloads/${ep_id}.html" \
			-H 'authority: 9anim.vip' \
			-H 'accept: */*' \
			-H 'x-requested-with: XMLHttpRequest' \
			-H 'sec-gpc: 1' \
			-H 'sec-fetch-site: same-origin' \
			-H 'sec-fetch-mode: cors' \
			-H 'sec-fetch-dest: empty' \
			-H "referer: ${selected_anime_url}" \
			-H 'accept-language: en-US,en;q=0.9' \
			--compressed
	)
	flag=0
	while read line; do
		case $line in
			'<td>'*)
				if [ $flag -eq 0 ]; then
					name=${name#<td>}
					name=${line%%<*}
					flag=1
				fi
				;;
			'<a'*)
				flag=0
				url=${line#*href=\"}
				url=${url%%\"*}
				echo "$name"
				echo "$url"
				;;
		esac
	done<<-!
	$html
	!
	mpv "$url"
}

case $selected_anime_url in
	'/movie/'*)
		ep_id=${selected_anime_url#/movie/}
		ep_id=${ep_id%%/*}
		ep_type=movie
		play_ep
		;;
	'/serie/'*)
		####################
		# SEASON SELECTION #
		####################
		html=$(
		curl -s "https://9anim.vip$selected_anime_url"
		)
		series_id=
		anime_count=0
		while IFS= read line; do
			case $line in
				'<button class="dropdown-item'*)
					anime_count=$((anime_count+1))
					alt_number=${line#*alt=\"}
					alt_number=${alt_number%%\"*}
					season_name=${line%<*}
					season_name=${season_name##*>}
					series_id=${series_id}${new_line}${alt_number}

					printf '[%d] %s\n' $anime_count "$season_name"
					;;
			esac
		done<<-!
		$html
		!
		series_id=${series_id#$new_line}

		read selected_season_count
		count=0
		while read id; do
			count=$((count+1))
			if [ $count -eq $selected_season_count ]; then
				selected_season_id=$id
			fi
		done<<-!
		$series_id
		!
		[ -z "$selected_season_id" ] && die "invalid choice"

		#####################
		# Episode SELECTION #
		#####################
		html=$(
		curl -s "https://9anim.vip/ajax/episodes/${selected_season_id}.html" \
		  -H 'authority: 9anim.vip' \
		  -H 'accept: */*' \
		  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36' \
		  -H 'x-requested-with: XMLHttpRequest' \
		  -H 'sec-gpc: 1' \
		  -H 'sec-fetch-site: same-origin' \
		  -H 'sec-fetch-mode: cors' \
		  -H 'sec-fetch-dest: empty' \
		  -H "referer: $selected_anime_url" \
		  -H 'accept-language: en-US,en;q=0.9' \
		  --compressed
		)

		ep_ids=
		anime_count=0
		while read line; do
			case $line in
				'<button class='*)
					anime_count=$((anime_count+1))
					data_id=${line#*'data-id='}
					data_id=${data_id%% *}

					data_title=${line#*'data-title="'}
					data_title=${data_title%%\"*}

					ep_ids=${ep_ids}${new_line}${data_id}

					printf '[%d] %s\n' $anime_count "$data_title"
					;;
			esac
		done<<-!
		$html
		!
		ep_ids=${ep_ids#$new_line}
		read selected_episode_count

		count=0
		while read id; do
			count=$((count+1))
			if [ $count -eq $selected_episode_count ]; then
				selected_episode_id=$id
			fi
		done<<-!
		$ep_ids
		!
		[ -z "$selected_episode_id" ] && die "invalid choice"

		ep_id=$selected_episode_id
		ep_type=serie
		play_ep
		;;
esac
