#!/usr/bin/python

import base64
import math
import time
import hashlib
import json
from Crypto.Cipher import AES
import sys

MASK = sys.argv[1]
BUILD_ID = sys.argv[2]
EPOCH = sys.argv[3]
PART_B = sys.argv[4]
QUERY_HASH = sys.argv[5]

def get_key() -> bytes:
    part_a = bytes.fromhex(MASK)
    part_b = base64.b64decode(PART_B)

    key = b""

    for a, b in zip(part_a, part_b):
        val = a ^ b
        key += val.to_bytes(1)

    return key

ts = math.floor((time.time() * 1000) / 300_000) * 300_000
aaReq_base = {
    "v": 1,
    "ts": ts,
    "epoch": int(EPOCH),
    "buildId": str(BUILD_ID),
    "qh": QUERY_HASH
}

K = f"{EPOCH}:{BUILD_ID}:{aaReq_base['qh']}:{ts}".encode()

IV_FULL = hashlib.sha256(K).digest()
IV = IV_FULL[:12]

KEY = get_key()
json_blob_string = json.dumps(aaReq_base, separators=(',',':'))

aes = AES.new(KEY, AES.MODE_GCM, nonce=IV)
cipher, tag = aes.encrypt_and_digest(json_blob_string.encode())

aaReq_bytes = b"\x01" + IV + cipher + tag
aaReq = base64.b64encode(aaReq_bytes).decode()

print(f'{aaReq} {KEY.hex()}')
