#!/bin/sh

REPO="https://github.com/pystardust/ani-cli.git"
case "$(uname)" in
    Darwin*)
        rm -rf "$(brew --prefix)/share/ani-cli"
        git clone "$REPO" "$(brew --prefix)/share/ani-cli"
        ln -sf "$(brew --prefix)/share/ani-cli/ani-cli" "$(brew --prefix)/bin/ani-cli"
        exit 0
        ;;
    Linux*)
        rm -rf "/usr/local/share/ani-cli"
        git clone "$REPO" "/usr/local/share/ani-cli"
        ln -sf "/usr/local/share/ani-cli/ani-cli" "/usr/local/bin/ani-cli"
        exit 0
        ;;
    *)
        printf "This installer is only for Linux and MacOS. Bye."
        exit 1
        ;;
esac
