#!/bin/sh

brew_base="$(brew --prefix)"
[ -d "${brew_base}" ] || printf "Your brew bin doesn't exist." && exit 1
case "$(uname)" in
    Darwin*)
        rm -rf "${brew_base}/share/ani-cli" "${brew_base}/bin/ani-cli"
        exit 0
        ;;
    Linux*)
        rm -rf "/usr/local/share/ani-cli" "/usr/local/bin/ani-cli"
        exit 0
        ;;
    *)
        printf "This uninstaller is only for Linux and MacOS. Bye."
        exit 1
        ;;
esac
