#!/usr/bin/python

import sys
import base64

from Crypto.Cipher import AES


key = bytes.fromhex(sys.argv[1])

tobeparsed = base64.b64decode(sys.argv[2])

iv = tobeparsed[1:13]
ciphertext = tobeparsed[13:-16]
tag = tobeparsed[-16:]

cipher = AES.new(key, AES.MODE_GCM, nonce=iv)
parsed = cipher.decrypt_and_verify(ciphertext, tag)
print(parsed)
