#!/bin/sh

play_episode () {
	video_url="$1"; refr="$3" trackma_title="$4"
	case "$(uname -s)" in
		Darwin*) /Applications/Syncplay.app/Contents/MacOS/syncplay "$video_url" -- --referrer="$refr" --force-media-title="$trackma_title";;
		MINGW*|*Msys) /c/Program\ Files\ \(x86\)/Syncplay/Syncplay.exe "$video_url" -- --referrer="$refr" --force-media-title="$trackma_title";;
		*) syncplay "$video_url" -- --referrer="$refr" --force-media-title="$trackma_title";;
	esac
}


# ani-cli syncplay player
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Project repository: https://github.com/pystardust/ani-cli
