#!/bin/sh

# License preamble at the end of the file

player_commands () {
	printf '%s %s' "ffmpeg" "aria2c"
}

download () {
	case $2 in
		*m3u8*)
			progress "Fetching Metadata.."
			[ -d "$tmpdir" ] || mkdir "$tmpdir"
			m3u8_data="$(curl -s "$2")"
			key_uri="$(printf "%s" "$m3u8_data" | sed -nE 's/^#EXT-X-KEY.*URI="([^"]*)"/\1/p')"
			m3u8_data="$(printf "%s" "$m3u8_data" | sed "/#/d")"
			printf "%s" "$m3u8_data" | grep -q "http" || relative_url=$(printf "%s" "$2" | sed "s|[^/]*$||")
			range=$(printf "%s\n" "$m3u8_data" | wc -l)

			if [ -n "$key_uri" ];then
				key=$(curl -s "$key_uri" | od -A n -t x1 | tr -d ' |\n')
				iv=$(openssl rand -hex 16)
			fi

			inf "pieces : $range"
			for i in $(seq "$range");do
				curl -s "${relative_url}$(printf "%s" "$m3u8_data" | sed -n "${i}p")" > "$tmpdir/$(printf "%04d" "$i").ts" && printf "\033[2K\r \033[1;32m✓ %s / %s done" "$i" "$range" &
				jobs -p > "$jobfile"
				while [ "$(wc -w "$jobfile")" -ge 35 ];do jobs > "$jobfile";sleep 0.05;done
			done
			wait

			if [ -n "$key_uri" ];then
				progress "Decrypting and Concatenating pieces into single file.."
				for i in "$tmpdir"/*;do
					openssl enc -aes128 -d -K "$key" -iv "$iv" -nopad >> video.ts < "$i"
				done
			else
				progress "Concatenating pieces into single file.."
				cat "$tmpdir"/* >> video.ts
			fi

			rm -rdf "$tmpdir" "$jobfile"
			progress "Encoding file to mp4 video.."
			ffmpeg -loglevel error -stats -i "video.ts" -c copy "$download_dir/$3.mp4"
			rm -f video.ts
			;;
		*)
			aria2c --check-certificate=false --summary-interval=0 -x 16 -s 16 --referer="$1" "$2" --dir="$download_dir" -o "${3}-${4}.mp4" --download-result=hide ;;
	esac
}

play_episode () {
	inf "Downloading $trackma_title"
	video_url="$1"; refr="$2" trackma_title="$3"
	if download "$refr" "$video_url" "$trackma_title"; then
		inf "Downloaded episode: $trackma_title"
	else
		err "Download failed episode: $trackma_title , please retry or check your internet connection"
	fi
}

jobfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-jobs"
download_dir="."
tmpdir="${XDG_CACHE_HOME:-$HOME/.cache}/ani-temp"
is_download=1;

# ani-cli download player
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Project repository: https://github.com/pystardust/ani-cli