#!/bin/sh

# ani-cli UI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Project repository: https://github.com/pystardust/ani-cli

UI_VERSION="1.0.0"
UI_NAME="classic"


ui_version_text() {
	inf "UI theme: $UI_NAME"
	inf "UI Version: $UI_VERSION"
}

update_ui () {
	update="$(curl -s "https://raw.githubusercontent.com/pystardust/ani-cli/master/ui")" || die "Connection error"
	update="$(printf '%s\n' "$update" | diff -u "$0" -)"
	if [ -z "$update" ]; then
		inf "UI is up to date :)"
	else
		if printf '%s\n' "$update" | patch "$0" - ; then
			inf "UI has been updated"
		else
			die "Can't update UI for some reason!"
		fi
	fi
}

get_input() {
	inf "$*"
	prompt "> "
}

retry () {
	err "$*"
	prompt "> "
}

# display an error message to stderr (in red)
err () {
	printf "\033[1;31m%s\033[0m\n" "$*" >&2
}

# display an informational message (first argument in green, second in magenta)
inf () {
	printf "\033[1;35m%s \033[1;35m%s\033[0m\n" "$1" "$2"
}

# prompts the user with message in $1-2 ($1 in blue, $2 in magenta) and saves the input to the variables in $REPLY and $REPLY2
prompt () {
	printf "\033[1;35m%s\033[1;35m%s\033[1;34m\033[0m" "$1" "$2"
	read -r REPLY REPLY2
}

selection_menu() {
	while read -r option line; do
		if [ "$option" = "q" ]; then
			menu_line_strong "$line" "$option"
		else
			menu_line_alternate "$line" "$option"
		fi
	done <<-EOF
	$*
	EOF
	prompt "> "
}

# displays an even (cyan) line of a menu line with $2 as an indicator in () and $1 as the option
menu_line_even () {
	printf "\033[1;36m(\033[1;36m%s\033[1;36m) \033[1;36m%s\033[0m\n" "$2" "$1"
}

# displays an odd (yellow) line of a menu line with $2 as an indicator in () and $1 as the option
menu_line_odd() {
	printf "\033[1;33m(\033[1;33m%s\033[1;33m) \033[1;33m%s\033[0m\n" "$2" "$1"
}

# display alternating menu lines (even and odd)
menu_line_alternate() {
	menu_line_parity=${menu_line_parity:-0}
	if [ "$menu_line_parity" -eq 0 ]; then
		menu_line_odd "$1" "$2"
		menu_line_parity=1
	else
		menu_line_even "$1" "$2"
		menu_line_parity=0
	fi
}

# displays a warning (red) line of a menu line with $2 as an indicator in [] and $1 as the option
menu_line_strong() {
	printf "\033[1;31m(\033[1;31m%s\033[1;31m) \033[1;31m%s\033[0m\n" "$2" "$1"
}
