#!/bin/sh

player_commands () {
	printf '%s' "mpv"
}

play_episode () {
	video_url="$1"; refr="$2" trackma_title="$3"
	inf "Currently playing $trackma_title"
	mpv "$video_url" --referrer="$refr" --force-media-title="$trackma_title" > /dev/null 2>&1 &
}
