#!/bin/sh

player_commands () {
	if ! uname -a | grep -qE '[Aa]ndroid';then
		printf '%s' "vlc"
	fi
}


play_episode () {
	video_url="$1"; refr="$2" trackma_title="$3"
	inf "Currently playing $trackma_title"
	if uname -a | grep -qE '[Aa]ndroid';then
		am start --user 0 -a android.intent.action.VIEW -d "$video_url" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "$trackma_title" > /dev/null 2>&1 &
	else
		vlc "$video_url"  --http-referrer="$refr" --meta-title "$trackma_title" --play-and-exit &> /dev/null & ## Redirect all output to /dev/null to make selection menu remain visible
	fi
}
